In [1]:
person = {
    "first" : "Corey",
    "last" : "Schafer",
    "email" : "CoreyMSchafer@test.com",
}

In [2]:
people = {
    "first" : ["Corey"],
    "last" : ["Schafer"],
    "email" : ["CoreyMSchafer@test.com"],
}

In [4]:
people = {
    "first" : ["Corey", "Jane", "John"],
    "last" : ["Schafer", "Doe", "Doe"],
    "email" : ["CoreyMSchafer@test.com", "JaneDoe@gmail.com", "JohnDoe@gmail.com"],
}

In [5]:
people['email']

['CoreyMSchafer@test.com', 'JaneDoe@gmail.com', 'JohnDoe@gmail.com']

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(people)

In [8]:
df

   first     last                   email
0  Corey  Schafer  CoreyMSchafer@test.com
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com

In [9]:
df.email

0    CoreyMSchafer@test.com
1         JaneDoe@gmail.com
2         JohnDoe@gmail.com
Name: email, dtype: str

In [13]:
df[["first",'email']]

   first                   email
0  Corey  CoreyMSchafer@test.com
1   Jane       JaneDoe@gmail.com
2   John       JohnDoe@gmail.com

In [18]:
df.loc[[0,1],'email']

0    CoreyMSchafer@test.com
1         JaneDoe@gmail.com
Name: email, dtype: str

In [16]:
df

   first     last                   email
0  Corey  Schafer  CoreyMSchafer@test.com
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com